### ISSUE TITLE
A bug in function `boundary` (pso.py).

### ISSUE THREAD

**Issue by lichunown** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#10]
The origin boundary will return the boundary `lb` and `ub` if `x` is overspill.
however, what we need limited is the **overspill value** instead of the whole **vector**.

**Comment by JingweiToo** [comment]
The lb and ub are designed based on articles, and they are also changeable based on other design structures. In addition, there are many ways to design the algorithm boundary, constraints based on specific problems. 

Moreover, I apply the same ub and lb to the whole vector because they are all representing the features. And I am using a threshold to determine the selected features.

**Comment by lichunown** [comment]
Thanks, but in my experiments, the limitation in overspill value would perform better.
And it is not make sense if we use the whole vertor to limit the boundary.

**Comment by JingweiToo** [comment]
Yes, I am using the simplest form. We may also change the boundary for each feature too
